# Generated by Django 4.1.7 on 2023-03-28 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transfer_amount", models.FloatField()),
                ("commission", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[("PAID", "paid"), ("FAILED", "failed")],
                        max_length=100,  # noqa E501
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiver",
                        to="wallet.wallet",
                        to_field="name",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender",
                        to="wallet.wallet",
                        to_field="name",
                    ),
                ),
            ],
        ),
    ]
