# Generated by Django 4.1.7 on 2023-04-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="commission",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12
            ),  # noqa E501
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[("PAID", "paid"), ("FAILED", "failed")],
                default="PAID",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transfer_amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
