# Generated by Django 4.1.7 on 2023-04-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0002_alter_transaction_commission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="commission",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[("PAID", "paid"), ("FAILED", "failed")],
                default="PAID",
                editable=False,
                max_length=100,
            ),
        ),
    ]
