# Generated by Django 4.1.7 on 2023-04-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0003_alter_transaction_commission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transfer_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12
            ),  # noqa E501
        ),
    ]
