# Generated by Django 4.1.7 on 2023-03-27 08:32

from django.db import migrations, models
import django.db.models.deletion
import wallet.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default=wallet.models.Wallet.generate_wallet_name,
                        max_length=8,
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Visa", "visa"), ("Mastercard", "mastercard")],
                        max_length=100,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "dollar"), ("EUR", "euro"), ("RUB", "ruble")],
                        max_length=3,
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wallet.user"
                    ),
                ),
            ],
            options={
                "ordering": ["user"],
            },
        ),
    ]
