# Generated by Django 4.2 on 2023-04-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0006_alter_wallet_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="currency",
            field=models.CharField(
                choices=[("USD", "dollar"), ("EUR", "euro"), ("RUB", "ruble")],
                default="EUR",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="type",
            field=models.CharField(
                choices=[("Visa", "visa"), ("Mastercard", "mastercard")],
                default="Visa",
                max_length=100,
            ),
        ),
    ]
