# Generated by Django 4.2 on 2023-04-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0007_alter_wallet_currency_alter_wallet_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=200
            ),
        ),
    ]
