# Generated by Django 4.2 on 2023-04-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0008_alter_wallet_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=200),
        ),
    ]
