# Generated by Django 4.2 on 2023-04-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0011_alter_wallet_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="currency",
            field=models.CharField(
                choices=[("USD", "dollar"), ("EUR", "euro"), ("RUB", "ruble")],
                default="EUR",
                max_length=3,
            ),
        ),
    ]
